name: "✨ Feature request"
description: Suggest a new feature or improvement for Web, Desktop, or Mobile
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature you would like to see
      placeholder: |
        Add support for automatic theme switching between light and dark mode.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature would be useful or what problem it solves
      placeholder: |
        It would improve usability and match the user's system preferences automatically.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select where this feature should be implemented
      options:
        - all platforms
        - desktop
        - web
        - mobile
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: Include any examples, mockups, or related information
      placeholder: |
        Example: Toggle in settings → "Follow system theme"
